In [61]:
"""Random maze generator"""

from random import shuffle, choice
from operator import add
from numpy import zeros as npz
import matplotlib.pyplot as plt


def build_maze(dims):
    """Generate a maze with rooms on intersections, corners, and dead-ends"""

    rules = [
        [0, 0, 0, 1], [0, 0, 1, 0], [0, 1, 0, 0], [1, 0, 0, 0],
        [1, 1, 1, 0], [1, 1, 0, 1], [1, 0, 1, 1], [0, 1, 1, 1],
        [1, 1, 1, 1], [1, 0, 1, 0], [1, 0, 0, 1], [0, 1, 1, 0],
        [0, 1, 0, 1]
    ]
    moves = [
        [(0, 2), (0, 1)], [(0, -2), (0, -1)],
        [(-2, 0), (-1, 0)], [(2, 0), (1, 0)]
    ]

#     x = choice([10, 12, 14, 18])
#     y = 148 // x
    x, y = dims
    maze = npz((x + 1, y + 1), dtype=int)
    grid = [(i, j) for i in range(1, x + 1, 2) for j in range(1, y + 1, 2)]
    path = [choice(grid)]
    rooms = []
    k = path[0]
    grid.remove(k)

    while grid:
        n = len(path)
        nsew = []

        for i in range(4):
            probe = tuple(map(add, moves[i][0], k))
            link = tuple(map(add, moves[i][1], k))
            nsew.append([probe, link])

        shuffle(nsew)
        for prb_lnk in nsew:
            probe, link = prb_lnk
            if probe in grid:
                maze[probe], maze[link] = 1, 1
                grid.remove(probe)
                path.extend(prb_lnk)
                break

        print(f"k: {k}\npath: {path[-1]}")
        if k == path[-1]:
            k = path[max(1, path.index(k) - 1)]
            print(f"deadend, backtracking to {k}\n")
        else:
            k = path[-1]

    for coord in path:
        i, j = coord
        neighbors = [
            maze[i-1, j],
            maze[i+1, j],
            maze[i, j-1],
            maze[i, j+1]
        ]

        if neighbors in rules:
            rooms.append(coord)
            maze[coord] = 2

    return maze, rooms


def draw_maze(maze):
    """display a maze"""
    plt.figure(figsize=(len(maze[0])//2, len(maze)//2))
    plt.pcolormesh(maze, cmap=plt.cm.get_cmap("tab20b"))
    plt.axis("equal")
    plt.axis("off")
    # plt.ion()
    plt.show(block=True)


In [62]:
maze, rooms = build_maze((30, 30))
draw_maze(maze)

k: (9, 29)
path: (10, 29)
k: (10, 29)
path: (10, 29)
deadend, backtracking to (11, 29)

k: (11, 29)
path: (11, 28)
k: (11, 28)
path: (11, 28)
deadend, backtracking to (11, 27)

k: (11, 27)
path: (12, 27)
k: (12, 27)
path: (12, 27)
deadend, backtracking to (13, 27)

k: (13, 27)
path: (13, 26)
k: (13, 26)
path: (13, 26)
deadend, backtracking to (13, 25)

k: (13, 25)
path: (13, 24)
k: (13, 24)
path: (13, 24)
deadend, backtracking to (13, 23)

k: (13, 23)
path: (12, 23)
k: (12, 23)
path: (12, 23)
deadend, backtracking to (11, 23)

k: (11, 23)
path: (11, 22)
k: (11, 22)
path: (11, 22)
deadend, backtracking to (11, 21)

k: (11, 21)
path: (11, 20)
k: (11, 20)
path: (11, 20)
deadend, backtracking to (11, 19)

k: (11, 19)
path: (10, 19)
k: (10, 19)
path: (10, 19)
deadend, backtracking to (9, 19)

k: (9, 19)
path: (9, 20)
k: (9, 20)
path: (9, 20)
deadend, backtracking to (9, 21)

k: (9, 21)
path: (9, 22)
k: (9, 22)
path: (9, 22)
deadend, backtracking to (9, 23)

k: (9, 23)
path: (8, 23)
k: (8, 2

path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtra

deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6,

path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7,

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deaden

k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deaden

k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deaden

path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtra

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deaden


k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deade

k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 

deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6, 3)
k: (6, 3)
path: (6, 3)
deadend, backtracking to (7, 3)

k: (7, 3)
path: (6,

KeyboardInterrupt: 

In [34]:
import numpy as np

def basic_maze(x, y):
    moves = np.array([[[0, 2], [0, 1]],
                      [[0, -2], [0, -1]],
                      [[-2, 0], [-1, 0]],
                      [[2, 0], [1, 0]]])

    maze = np.zeros((x + 1, y + 1), dtype=int)
    grid = [(i, j) for i in range(1, x + 1, 2) for j in range(1, y + 1, 2)]
    path = [choice(grid)]
    current_position = path[0]
    grid.remove(current_position)

    while grid:
        n = len(path)
        nsew = np.array(current_position) + npmoves

        # shuffle(nsew) # can't shuffle ndarray
        for prb_lnk in nsew:
            probe, link = prb_lnk
            if probe in grid:
                maze[probe], maze[link] = 1, 1
                grid.remove(probe)
                path.extend(prb_lnk)
                break

        if n == len(path):
            current_position = path[max(1, path.index(current_position) - 1)]
        else:
            current_position = path[-1]
    return maze

In [46]:
# draw_maze(basic_maze(6, 6))
moves = [
    [(0, 2), (0, 1)], [(0, -2), (0, -1)],
    [(-2, 0), (-1, 0)], [(2, 0), (1, 0)]
]

npmoves = np.array(moves)
print(npmoves)
choice(npmoves)

[[[ 0  2]
  [ 0  1]]

 [[ 0 -2]
  [ 0 -1]]

 [[-2  0]
  [-1  0]]

 [[ 2  0]
  [ 1  0]]]


array([[2, 0],
       [1, 0]])